global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Application
  - job_name: 'store-order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 10s

  # MySQL (if using mysqld_exporter)
  - job_name: 'mysql'
    static_configs:
      - targets: ['host.docker.internal:9104']

  # Redis (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']

  # Kafka (if using kafka_exporter)
  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9308'] 