spring:
  # Test Database Configuration (H2)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA Configuration for Tests
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Disable Liquibase for tests
  liquibase:
    enabled: false
  
  # Redis Configuration for Tests
  redis:
    host: localhost
    port: 6379
    timeout: 1000ms
  
  # Kafka Configuration for Tests
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Test Configuration
store:
  jwt:
    secret: test-secret-key-for-testing-purposes-only
    expiration: 3600000
    issuer: test-store-service
    audience: test-store-clients
  order:
    max-items-per-order: 10
    max-retry-count: 2
    retry-interval-minutes: 1
    timeout-minutes: 5
  redis:
    lock:
      timeout-seconds: 10
      idempotency-ttl-hours: 1

# Logging for Tests
logging:
  level:
    com.store: DEBUG
    org.springframework.kafka: WARN
    org.springframework.data.redis: WARN
    org.hibernate.SQL: DEBUG 